### PR TITLE
Revert "util: Spoof Ada and later GPUs as Ampere for Ghost of Tsushima"

### PR DESCRIPTION
**Pull request by Saancreed**
This reverts commit f86f56b24737d117098a80133516edfb553fe39a.

To be merged after DLSS FG support is in place. Let me know if I should actually write a new commit message.

### CODE REVIEW

**Comment by jp7677** [comment]
Thanks, PR is good ofc. Would be nice if the commit message at least briefly states why we don't need this any longer.

**Review by jp7677 — APPROVED** [review]

**Comment by shelterx** [comment]
The workaround was made for a reason, are we sure it isn’t needed?

https://github.com/HansKristian-Work/vkd3d-proton/issues/2008

**Comment by Saancreed** [comment]
@shelterx The cause of this issue will be gone from Proton soon so yes, we are… fairly confident about it.

But feel free to verify this and report back; while I can no longer notice the problem myself, another confirmation would be appreciated. Just don't forget to add Liam's D3DKMT patches to the mix and install nvofapi64.dll into Proton prefix.

**Comment by shelterx** [comment]
@Saancreed seems to work yes from what I could tell, with DLSS FG and Reflex On

**Comment by Saancreed** [comment]
That's great, thanks for checking!

**Pull request merged**
