### PR TITLE
Implement NVAPI_GetLogicalGPUFromPhysicalGPU

### PR DESCRIPTION
**Pull request by nvetillison**
Implement NVAPI_GetLogicalGPUFromPhysicalGPU as the inverse of NVAPI_GetPhysicalGPUsFromLogicalGPU.

### CODE REVIEW

**Comment by jp7677** [comment]
Thanks for the contribution. Could you please state your motivation behind this PR and what is solves in the real world?

**Comment by nvetillison** [comment]
Sure! The function NvAPI_GPU_GetAdapterIdFromPhysicalGpu was deprecated with NvAPI release 520, and the suggested alternative is to replace it with a call to NvAPI_GetLogicalGPUFromPhysicalGPU, and then use NvAPI_GPU_GetLogicalGpuInfo to get the adapter ID.

This change is proposed in the interest of supporting applications that use the new code path.

**Comment by jp7677** [comment]
Do you know any applications/titles that already use that path?

**Comment by jp7677** [comment]
@nvetillison sry, I didn't recognized the first two letter in your github name ;)
Could you please prefix the commit message with `nvapi:`? Otherwise, LGTM!

**Comment by jp7677** [comment]
Landed on master and thanks a lot for already taking this project into account!

**Comment by oscarbg** [comment]
@liam-middlebrook curious even latest DLSS 3.1.10 SDK windows demo (https://github.com/NVIDIA/DLSS/releases/tag/v3.1.10) isn't using it, for testing?
anyway hope NV is working on DLSSG (frame generation) Wine support, and can get some cool anouncement soon (later this year?)

**Pull request merged**
