### PR TITLE
vk-headers: Update external/Vulkan-Headers to 1.2.182

### PR DESCRIPTION
**Pull request by rgc183**
Signed-off-by: Roshan Chaudhari <rochaudhari@nvidia.com>

Reviewed-by: Liam Middlebrook <lmiddlebrook@nvidia.com>

### CODE REVIEW

**Comment by jp7677** [comment]
Thanks for the contribution, looks good.
You are using different usernames for commits and GitHub interaction, this is intended?

**Comment by rochaudhari** [comment]
If we do not need to be fixed now, I can try it later.

**Comment by jp7677** [comment]
> If we do not need to be fixed now, I can try it later.

Sorry, I did not understood what you propose, could you please rephrase?

**Comment by rochaudhari** [comment]
I need to figure out why "You are using different usernames for commits and GitHub interaction" is happening. Setting git user.name did not work. I am planning to look at it later, can we merge this ?

**Comment by jp7677** [comment]
Thanks for the rewording, got it.
Actually I would prefer if you could fix this before merging. Changing this afterwards once this has been landed in master is messy. 
Since this is just one commit, using `git commit ––amend ––author=“...”` and then force push should do the trick.

**Comment by rochaudhari** [comment]
Opened new one: https://github.com/jp7677/dxvk-nvapi/pull/24 issue was due to multiple accounts :/

**Pull request closed without merging**
