### PR TITLE
NvOFInstanceD3D12: Implement input/output fence points

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Needed for older versions of nvngx_dlssg.dll where OF buffer registration was synchronized with GPU work.

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Thanks to @adamdmoss for reporting this bug. If you're able to confirm this resolves your issue I'd appreciate it.

**Review by jp7677 — APPROVED** [review]

**Comment by adamdmoss** [comment]
Gollum is very happy now.  Thanks!

**Comment by adamdmoss** [comment]
Oh, it fixes the rat game crash too!  Hooray!  It has weird unpleasant out-of-order frame issues when FG is enabled but that's better than being in a crashloop.

**Comment by adamdmoss** [comment]
> Gollum is very happy with this PR. Thanks!

Oops, spoke too soon.  It has the same problem as Plague Tale Requiem with this fix; it no longer crashes but it eventually starts presenting frames out-of-order.  Just took longer to repro (like a couple of minutes) with Gollum.

**Comment by adamdmoss** [comment]
So -> IMHO this fix is a definite improvement (visual glitches are an improvement over complete crashing) and I'd love it to land, but it either reveals or causes further issues with the two titles it stops crashing so it's not an ultimate fix.

**Comment by jp7677** [comment]
@liam-middlebrook Do you want to address Adams remaining points as part of this PR or do you prefer if we land this now as intermediate improvement?

**Review by Saancreed — APPROVED** [review]

**Comment by liam-middlebrook** [comment]
> @liam-middlebrook Do you want to address Adams remaining points as part of this PR (if it is even doable here) or do you prefer if we land this now as an intermediate improvement?

I don't think we should wait for that. There are a few different modules at work here, and the issues Adam describes don't sound like they would be due to `nvofapi64.dll`.

**Comment by jp7677** [comment]
Thanks!

**Pull request merged**
